# Generated by Django 4.2.5 on 2024-03-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_category_developer_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
