# Generated by Django 4.2.5 on 2024-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_developer_info_developer_year_platform_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
