# Generated by Django 4.2.5 on 2024-03-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Game.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Game.developer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Game.phase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Game.platform'),
            preserve_default=False,
        ),
    ]
