# Generated by Django 4.2.5 on 2024-03-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_games_category_games_developer_games_phase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
