# Generated by Django 4.2.5 on 2024-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='age',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='director',
            name='info',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
