# Generated by Django 4.2.5 on 2024-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0006_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='director',
            name='info',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
